### ISSUE TITLE
Ranking Tasks: roter Knopf sollte erst funktionieren, wenn alle entities in den Antwortfeldern einsortiert sind

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#114]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browsers: R Version

**Additional context**

**Comment by kalaschnik** [comment]
8ca3d2f14cbb604dcaa9f92715deac3d5a9a7c68
