### ISSUE TITLE
Ranking Tasks: sollte eins nach dem anderen einsortierbar sein, so dass audio erst fertig werden muss. Genau wie bei moral circle (müsste da auch angepasst werden), dass man nicht alle direkt hintereinander klicken kann

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browsers: R Version

**Additional context**

**Comment by kalaschnik** [comment]
8ca3d2f14cbb604dcaa9f92715deac3d5a9a7c68
