### ISSUE TITLE
Karri/rating questions: sometimes if the animals arent wholly on the square you need to adjust them a little to get the red next arrow to activate

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#132]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browsers: R Version

**Additional context**

**Comment by kalaschnik** [comment]
Let’s talk about the how aggressive the hitTest is

**Comment by kalaschnik** [comment]
There is a visual cue telling you if you hit the box...
