### ISSUE TITLE
Übergabe: - homebrew installieren; Umwandlung von pinda videos dokumentieren; Kombinierung von mp3 und mp4 Dokumentation

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#144]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kalaschnik** [comment]
8ca3d2f14cbb604dcaa9f92715deac3d5a9a7c68
