### ISSUE TITLE
s-practice-dilemma: ja /nein kann geklickt werden bevor optionen vorgestellt sind

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#177]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browsers: R Version

**Additional context**

**Comment by kalaschnik** [comment]
8ca3d2f14cbb604dcaa9f92715deac3d5a9a7c68
