### ISSUE TITLE
Rankings + Ball practice + ball dilemma: shrink ball or animals/humans when dropped (sorry wahrscheinlich doppelt) + new cool circle also for ball demo and ball practice

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#179]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browsers: R Version

**Additional context**

**Comment by kalaschnik** [comment]
8ca3d2f14cbb604dcaa9f92715deac3d5a9a7c68
