### ISSUE TITLE
s-reasoning: pinda immer da, ab da wo die antwortmöglichkeit erkläret wird (z.B. schreib deine erklärung in das feld oder wenn die buttns erklärt werden), neutraler pinda fehlt auf human vs cat,. auch beim dritten ist pinda nicht immer da.

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#188]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browsers: R Version

**Additional context**

**Comment by kalaschnik** [comment]
8ca3d2f14cbb604dcaa9f92715deac3d5a9a7c68
