### ISSUE TITLE
adult: reasoning: textinput: pinda video fehlt wenn man antwortmodus wechselt, some glitch with switch button. neutraler pinda nicht immer da bzw.erstmit großer verzögerung

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#195]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browsers: R Version

**Additional context**

**Comment by kalaschnik** [comment]
8ca3d2f14cbb604dcaa9f92715deac3d5a9a7c68
