### ISSUE TITLE
s-reasoning: 1 hu vs 1 cow; loop beim falschen pinda, doppeltes audio, kann nicht von text auf audio input wechseln, procedure bleibt stecken, keine antwort möglich.

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#200]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browsers: R Version

**Additional context**

**Comment by kalaschnik** [comment]
8ca3d2f14cbb604dcaa9f92715deac3d5a9a7c68
