### ISSUE TITLE
durch links/rechts wischen kommt man auf die landing page aber nicht wieder zurück -> disable in browser, also that downloads are shown.

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#207]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browsers: R Version

**Additional context**

**Comment by kalaschnik** [comment]
Not a bug; it’s the way browsers go back. Same with showing downloads. In some browsers you may be able to hide showing downloads, or with an extension https://chrome.google.com/webstore/detail/autohidedownloadsbar/gkmndgjgpolmikgnipipfekglbbgjcel?hl=en
