### ISSUE TITLE
s-task: export one line per entitiy

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#22]
mct_animal: cow, cat, dog, fish, sheep, pig, chicken, rabbit, adult_f, adult_m, elderly, child
mct_included: true/false (logical, true=included, false=not included)

**Comment by kalaschnik** [comment]
Resolved in af247811d456a3b06e4de17eab5af3cc98a9ec4d

Reponse data looks like this

```
cat: "inner"
chicken: "middle"
cow: undefined
dog: "inner"
duration: 10320
goldfish: "outer"
human: "inner"
knownAnimals: Array(5) [ "chicken", "dog", "sheep", … ]
pig: undefined
rabbit: undefined
sheep: "outer"
unknownAnimals: Array(3) [ "pig", "cow", "rabbit" ]

```
