### ISSUE TITLE
s-task: das müsste mit dem anderen issue für später zusammenhängen, dann nur innerhalb der Kreise weiterplatziert werden können

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#241]
<img width="1307" alt="Screenshot 2023-04-08 at 14 51 56" src="https://user-images.githubusercontent.com/95216156/230722212-72d9305d-7820-4077-b3ea-b38b3f29ea33.png">

**Comment by kalaschnik** [comment]
ja, duplicate #180
