### ISSUE TITLE
quitbeforeEnd - wann ist das true? 

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#252]

**Comment by kalaschnik** [comment]
The variable will be true, when the user is not in dev mode, hasn’t finished the procedures, quits the browser window, and confirms the exit warning.

false will be overwritten to true when the above rules apply. Defined here:
https://github.com/ccp-eva/matt/blob/develop/src/util/init.ts#L175

Here, after the entire procedure loop, the exit prompt will be disabled:
https://github.com/ccp-eva/matt/blob/develop/src/procedure/procedure.ts#L177
