### ISSUE TITLE
audio chunks overlap

### ISSUE THREAD

**Issue by NoemiThiede** [ccp-eva/matt#80]
Audiospuren warden bei slide-Übergängen immer mal wieder abgeschnitten
	- z.B. 'Das hast du dir gut gemerkt' und dem Übergang zu s-task
- gerade bei `wie wichtig sind dir schweine' - hier hat die überleitung zum 
comprehension check das abgeschnitten
- Reaktion 'das hast du dir gut gemerkt' war gerade abgeschnitten und es ging 
 automatisch weiter zur nächsten slide

**Comment by kalaschnik** [comment]
8ca3d2f14cbb604dcaa9f92715deac3d5a9a7c68
